apiVersion: v1
kind: Service
metadata:
  name: hello-dev
  labels:
    app: hello-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-dev
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dev
  labels:
    app: nginx-dev
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-dev
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prod
  labels:
    app: nginx-prod
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-prod
---
apiVersion: v1
kind: Service
metadata:
  name: hello-prod
  labels:
    app: hello-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: hello-prod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-dev
  name: hello-dev
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: hello-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-dev
  name: nginx-dev
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hello-prod
  name: hello-prod
spec:
  containers:
  - image: gcr.io/google-samples/hello-app:1.0
    name: hello-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-prod
  name: nginx-prod
spec:
  containers:
  - image: nginx:1.14.2
    name: nginx-prod
    ports:
    - containerPort: 80 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob-developer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice-ops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eve-auditor

